<?php
// dozrmvr od hpzfrm
// Generated by issax_pi on Tue, 14 Feb 2023 16:25:12 +0600 in bunkernine
// Written successfully in C:/xampp/htdocs/ext-siraj
include $_SERVER["DOCUMENT_ROOT"]."/Server-picox.php";